# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"

    # ✅ Configuration correcte des sessions
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 0

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
