services:
  - type: web
    name: symfony-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    startCommand: "" # Dockerfile s'occupe de démarrer le serveur
    envVars:
      - key: APP_ENV
        value: prod
