# config/services.yaml
parameters:

services:
    # ============================================================
    # ⚙️ CONFIGURATION PAR DÉFAUT
    # ============================================================
    _defaults:
        autowire: true # Injection automatique des dépendances
        autoconfigure: true # Enregistre automatiquement les tags requis
        bind:
            $projectDir: "%kernel.project_dir%"

    # ============================================================
    # 📦 AUTO-DÉCOUVERTE DES SERVICES DU DOSSIER SRC/
    # ============================================================
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Migrations/"
            - "../src/Tests/"
            - "../src/Kernel.php"

    # ============================================================
    # 🔐 AUTHENTICATOR PERSONNALISÉ (formulaire de connexion)
    # ============================================================
    App\Security\LoginFormAuthenticator:
        arguments:
            $router: "@router"
            $passwordHasher: "@security.user_password_hasher"
            $userRepository: '@App\Repository\UserRepository'
            $entityManager: "@doctrine.orm.entity_manager"

    # ============================================================
    # 🧠 LISTENER : ENREGISTRE LES TENTATIVES DE CONNEXION
    # ============================================================
    App\EventListener\LoginAttemptListener:
        tags:
            # 🔴 Tentatives de connexion échouées
            - {
                  name: kernel.event_listener,
                  event: Symfony\Component\Security\Core\Event\AuthenticationFailureEvent,
                  method: onAuthenticationFailure,
              }

            # 🟢 Connexions réussies
            - {
                  name: kernel.event_listener,
                  event: Symfony\Component\Security\Http\Event\InteractiveLoginEvent,
                  method: onInteractiveLogin,
              }
            - {
                  name: kernel.event_listener,
                  event: kernel.request,
                  method: checkSessionContext,
              }

    # ============================================================
    # 📬 AUTRES SERVICES PERSONNALISÉS (ajoute ici si besoin)
    # ============================================================
    # Exemple :
    # App\Service\MailService: ~
